### ISSUE TITLE
NameError when run in Virtual Environment

### ISSUE THREAD

**Issue by stta5059** [NASA-IMPACT/csdap-bulk-download#16]
I'm having trouble running `csdap-bulk-download` on the x86_64 Linux platform (Debian 10) using python3 Virtual Environments. The setup and error are some variation of the following:

Installing into the venv csdap 
```bash
python3 -m venv csdap
. csdap/bin/activate
# My venv doesn't come with wheel, so install it manually
pip3 install wheel
# Removed --user since I want this in the venv
pip3 install https://github.com/NASA-IMPACT/csdap-bulk-download/archive/main.zip
csdap-bulk-download order.csv -o /data/csdap/
```

Results of running in the Anaconda install ~/csdap3
```
~$ csdap-bulk-download order.csv -o /data/csdap/
Traceback (most recent call last):
  File "/home/user/csdap3/bin/csdap-bulk-download", line 5, in <module>
    from csdap_bulk_download.cli import cli
  File "/home/user/csdap3/lib/python3.9/site-packages/csdap_bulk_download/cli.py", line 12, in <module>
    from .csdap import CsdapClient
  File "/home/user/csdap3/lib/python3.9/site-packages/csdap_bulk_download/csdap.py", line 19, in <module>
    class CsdapClient:
  File "/home/user/csdap3/lib/python3.9/site-packages/csdap_bulk_download/csdap.py", line 88, in CsdapClient
    **_,
NameError: name '_' is not defined
```

So far I've encounter this on:
* System Python (3.7.3)
* System Python created venv, then built/installed stock Python 3.10.2 into the venv.
* Anaconda 3 (Python 3.9.7)

I have not tried this using an isolated user account and installing with `pip3 install --user`.

`/home/user` is an ext4 filesystem. `/data/csdap` is a ZFS dataset owned by user. Please let me know if you need additional details.

**Comment by alukach** [comment]
@stta5059 Thanks for bringing this to our attention.  Would you please reinstall the module and try again?
