### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by stta5059** [NASA-IMPACT/csdap-bulk-download#22]
I'm running the `csdap-bulk-download` on Debian 10 with Python 3.7.3 and the program is killed after 6-10 hours by the Out Of Memory killer. This is surprising as the system I'm running the downloader on has 256 GB of RAM.

The downloader seems to download about 146 GB of data before the OOM killer reaps the process. The downloader is outputting to a folder on a ZFS array backed by spinning disks. I've observed the python3 process in top and it grows steadily in memory consumption. 

Please let me know if you need any additional details.

**Comment by alukach** [comment]
@stta5059 Thanks for this ticket.  I've put together a fix that I'd be appreciative if you'd test.  You can install it via the following:

```
pip3 install https://github.com/NASA-IMPACT/csdap-bulk-download/archive/bugfix/avoid-memory-issues.zip
```

Please let me know if this helps avoid the excessive memory consumption that you're seeing.

**Comment by stta5059** [comment]
Hello @alukach thanks for the quick turn around on this fix! At the moment (running 1 hour), I'm seeing 26 GB used and growing. It will take several hours to reach the point the OOM killer kicks in, so perhaps it will reach a steady state before that happens... What is the memory usage you'd expect from the downloader process?

**Comment by alukach** [comment]
@stta5059 Yeah, 26 GB is still _way_ higher than I would have ever expected...  Are you sure that's   I am still kind of scratching my head as to what could be causing it. What's going on so far is that if you don't specify a concurrency for the command (`-c`), then script will spin up 5 workers for every CPU on your machine.  This seems reasonable being that the process of downloading data is far more IO bound than CPU bound.  When we put the script together, we made best effort to be memory conservative (eg streaming the file from the network to disk in small chunks).  It's possible that this isn't as effective as we had hoped for, but I'm surprised that you're seeing such high usage.

I have pushed another small change that should hopefully help cleanup memory usage after each file is downloaded.  You can make use of this by re-entering the same install command mentioned above.

Can you run this script with `-v` to increase verbosity and let me know what the first 10 lines of the output are?  Additionally, can you let me know what data you're downloading so I may try to reproduce this locally?

**Comment by stta5059** [comment]
@alukach I did install it overtop of the old version pulled from the `main` branch. I'll run again with the new patch and if I observe the memory climbing again I'll try in a fresh venv.

The process is consuming 130-150 percent of one CPU core (of which there are 12, so a total of 1200% available). Since the OOM killer was invoked with only about 146 GB downloaded the first time, and I have 256 GB total RAM in the system (of which about half should be used for ARC in ZFS), it seems the program is keeping all the downloaded data in RAM. This is with the Debian-provided Python 3.7.3. I could try with source-built vanilla Python 3.10 if you think that'll help.

 ```
Earthdata Login username: Earthdata Login password:2022-03-05 00:31:06,999:Authenticating with Earthdata Login...
2022-03-05 00:31:07,292:Exchanging authorization code for access token...
2022-03-05 00:31:08,041:Detected legacy CSV.
2022-03-05 00:31:08,042:Detected legacy CSV.
2022-03-05 00:31:08,042:Detected legacy CSV.
2022-03-05 00:31:08,043:Detected legacy CSV.
2022-03-05 00:31:08,043:Downloading 420/2021-01-28T02-52-40_FM107_G03_antPOD_podTec/spire_iono_L1B_podTec_v06.02_2021-01-28T02-52-40_FM107_G03_antPOD.nc...
2022-03-05 00:31:08,043:Detected legacy CSV.
2022-03-05 00:31:08,046:Detected legacy CSV.
2022-03-05 00:31:08,046:Detected legacy CSV.
```

My understanding is these are GNSS-R observations from the SDX mission (I'm not the one consuming the data, I'm just the sysadmin). Order number 420.

**Comment by stta5059** [comment]
So, in the time it took to type the above reply I hit 5.6 GB used. I created a fresh venv and installed the zip file via pip. Usage seems to be growing more slowly. I'll report back once it's had a chance to run for a while.

**Comment by stta5059** [comment]
The latest version has been running since Friday and is still only consuming ~300 MB of RAM. It seems this issue is resolved.

**Comment by stta5059** [comment]
This issue does seem to be resolved, however, I am now seeing `2022-03-08 16:37:12,276:420/2020-11-25T01-03-21_FM102_G09_antPOD_podTec/spire_iono_L1B_podTec_v06.02_2020-11-25T01-03-21_FM102_G09_antPOD.nc: Failed to download. Insufficient user quota to download the selected assets.` Is this related to the patched software, or is this something on the server side I need to contact the PI about?
