### ISSUE TITLE
Download starts over after crash.

### ISSUE THREAD

**Issue by stta5059** [NASA-IMPACT/csdap-bulk-download#23]
This issue was brought to light due to #22. The platform I'm running on is Debian 10, Python 3.7.3.

The order I'm downloading is quite large, so accumulating statistics is quite time consuming as the storage volume is on traditional spinning drives. What I've gathered so far:

* The program is run as `csdap-bulk-download order_xyz.csv -o /data/output/folder`. 
* /data/output/folder is on a ZFS volume. This is a local volume (eg not NFS mounted)
* The order_xyz.csv file has some 17 million lines
* `find /data/output/folder` returns around 9 million files and folders
* `find /data/output/folder -type f` returns 114,412 files
* `du -hs /data/output/folder` returns 146 GB
* I've run the downloader several dozen times.
* After several runs over the course of a week, the output of `find /data/output/folder -type f` remains at 114,412.

It seems the downloads start back at the beginning of the list after the process is reaped by the OOM killer.

**Comment by alukach** [comment]
Thanks @stta5059!  Upon review, it does seem correct that the script was not skipping files as intended.  We have applied a fix that should resolve this issue.  Please reinstall the script and report back if the issue is not resolved.
