### ISSUE TITLE
Update to support quotas download endpoint

### ISSUE THREAD

**Issue by alukach** [NASA-IMPACT/csdap-bulk-download#6]
This script downloads items from `download/:order_id/:scene_id/:asset_type`.  We should instead be downloading data with a `:collection_id` rather than an `:order_id`.

**Comment by Tammo-Feldmann** [comment]
@alukach I think we can close this issue since you already took care of it. (Just some house keeping)

**Comment by alukach** [comment]
@Tammo-Feldmann I think we should still keep this open until we're ready to merge #13 (I accidentally merged #12).
